[
  {
    listItem: "School Days",
    description: "Basic School Setting Not my cup of tea",
    rating: "F",
    genre: "school",
    user_id: 1,
  },
  {
    listItem: "The Case Files of Jeweler Richard",
    description:
      "This show brings up the idea of justice and makes you think about society,racism, and general hate within society.",
    rating: "B",
    genre: "slice of life",
    user_id: 1,
  },
  {
    listItem: "Kakushigoto",
    description:
      "This is an anime about a dad trying to shield his daughter from his embarassing profession",
    rating: "C",
    genre: "comedy",
    user_id: 1,
  },
  {
    listItem: "Katekyo Hitman Reborn",
    description:
      "This is a great story about a weak highschool student being forced to become a mafia boss. It has many great moments and many great characters",
    rating: "A",
    genre: "action",
    user_id: 1,
  },
  {
    listItem: "Psycho Pass",
    description:
      "Interesting show that brings up concepts of justice, law, and overall philosophy ",
    rating: "A",
    genre: "psychological",
    user_id: 1,
  },
  {
    listItem: "Blue Exorcist",
    description: "A young man who lost his dad trying to kill satan",
    rating: "A",
    genre: "shounen",
    user_id: 1,
  },
  {
    listItem: "Attack On Titan",
    description: "An anime about a young man trying to avenge his mother",
    rating: "A",
    genre: "shounen",
    user_id: 1,
  },
  {
    listItem: "Barakamon",
    description: "A slice of life that explores the human spirit",
    rating: "A",
    genre: "slice of life",
    user_id: 1,
  },
  {
    listItem: "Fire Force",
    description: "Classic action stuff",
    rating: "B",
    genre: "action",
    user_id: 1,
  },
  {
    listItem: "Dragon Ball Super",
    description: "I love the characters but the plot is below average",
    rating: "C",
    genre: "shounen",
    user_id: 1,
  },
  {
    listItem: "Dragon Ball Z",
    description: "Amazing Characters Amazing Plot",
    rating: "A",
    genre: "shounen",
    user_id: 1,
  },
  {
    listItem: "Darwins Game",
    description:
      "A gruesome story about a death game. Its like mirai nikki on steriods",
    rating: "S",
    genre: "action",
    user_id: 1,
  },
  {
    listItem: "Magi",
    description: "Adventure story with a bit of politics",
    rating: "B",
    genre: "adventure",
    user_id: 1,
  },
  {
    listItem: "Fruits Basket",
    description:
      "A slice of life with a hint of romance. Wonderful character development for one of the main characters kou",
    rating: "B",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "Rikei ga Koi ni Ochita",
    description:
      "A romance about two scientists trying to prove they are in love with each other. The premise is great but it has some really cringy parts",
    rating: "C",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "Hyouka",
    description: "I dropped it after the second episode",
    rating: "F",
    genre: "mystery",
    user_id: 1,
  },
  {
    listItem: "KimiSui",
    description:
      "I want to eat your pancreas is a story about a student who has a couple months left to live. It is beautiful and i almost cried",
    rating: "S",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "The Daily Life Of Immortal King",
    description: "Parts were great others were a trainwreck",
    rating: "C",
    genre: "action",
    user_id: 1,
  },
  {
    listItem: "3D Girlfriend",
    description: "Story about otaku falling in love. Its alright",
    rating: "B",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "Gamers",
    description: "A crazy love pentagon OoO",
    rating: "B",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "Death Note",
    description: "The first 25 episodes were legendary",
    rating: "A",
    genre: "drama",
    user_id: 1,
  },
  {
    listItem: "Nanana's Buried Treasure",
    description: "Fun little adventure series",
    rating: "B",
    genre: "adventure",
    user_id: 1,
  },
  {
    listItem: "Accel World",
    description: "This show was fucking stupid",
    rating: "D",
    genre: "ecchi",
    user_id: 1,
  },
  {
    listItem: "Highschool Of the Dead",
    description: "zombies in anime is always a win",
    rating: "C",
    genre: "action",
    user_id: 1,
  },
  {
    listItem: "Ahiru no Sora",
    description: "Really good chracters great basketball",
    rating: "B",
    genre: "sports",
    user_id: 1,
  },
  {
    listItem: "The 8th son",
    description: "meh its funny",
    rating: "C",
    genre: "comedy",
    user_id: 1,
  },
  {
    listItem: "One Piece",
    description:
      "I love it its just so much material so i wouldn't ever reccomend it to someone",
    rating: "A",
    genre: "shounen",
    user_id: 1,
  },
  {
    listItem: "My Hero Academia",
    description:
      "The animation the characters, the world, its just classic shounen",
    rating: "S",
    genre: "shounen",
    user_id: 1,
  },
  {
    listItem: "Demon Slayer",
    description:
      "Really Great animation and cool characters. Right now its at A but maybe if it impresses me next season it will move up to S",
    rating: "A",
    genre: "shounen",
    user_id: 1,
  },
  {
    listItem: "Black Clover",
    description: "First half lack luster, second half impressive",
    rating: "C",
    genre: "shounen",
    user_id: 1,
  },
  {
    listItem: "Boruto",
    description: "WTF",
    rating: "F",
    genre: "shounen",
    user_id: 1,
  },
  {
    listItem: "Naruto",
    description: "I have such nostalgia for this show",
    rating: "B",
    genre: "shounen",
    user_id: 1,
  },
  {
    listItem: "Seven Deadly Sins",
    description: "Really deep characters. Manga goes nuts",
    rating: "A",
    genre: "shounen",
    user_id: 1,
  },
  {
    listItem: "Dr Stone",
    description:
      "Really interesting premise,but thats all the interests me the characters and plot are generic",
    rating: "C",
    genre: "shounen",
    user_id: 1,
  },
  {
    listItem: "Nyan Koi",
    description: "Romance its good the story is over tho",
    rating: "C",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "One Punch Man",
    description: "Its funny id give it a solid c",
    rating: "C",
    genre: "comedy",
    user_id: 1,
  },
  {
    listItem: "Tokyo Ghoul",
    description: "Rip kanikei",
    rating: "B",
    genre: "horror",
    user_id: 1,
  },
  {
    listItem: "Haikyuu",
    description: "I love the characters and the world",
    rating: "A",
    genre: "sports",
    user_id: 1,
  },
  {
    listItem: "Kuroko no Basket",
    description: "the characters do some crazy stuff I enjoyed it tho",
    rating: "B",
    genre: "sports",
    user_id: 1,
  },
  {
    listItem: "Sword Art Online",
    description: "The first arc was good and the rest was... special",
    rating: "C",
    genre: "action",
    user_id: 1,
  },
  {
    listItem: "Fairy Tail",
    description: "Loved fairy tail it just is slow paced",
    rating: "C",
    genre: "action",
    user_id: 1,
  },
  {
    listItem: "Food Wars",
    description: "Good plot ;_)",
    rating: "B",
    genre: "school",
    user_id: 1,
  },
  {
    listItem: "Nisekoi",
    description: "I was suprised by how much i enjoyed this one",
    rating: "B",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "Assassination Classroom",
    description:
      "the premise is the teacher can wipe out the earth whenver but he wanted to teach some kids",
    rating: "A",
    genre: "action",
    user_id: 1,
  },
  {
    listItem: "Diamond no Ace",
    description: "Not a fan",
    rating: "D",
    genre: "sports",
    user_id: 1,
  },
  {
    listItem: "JoJo's Bizzare Adventure",
    description:
      "I loved the art, the characters, honestly glad that JoJo's is in my life",
    rating: "A",
    genre: "action",
    user_id: 1,
  },
  {
    listItem: "Erased",
    description: "Overall good story the ending came out of nowhere tho",
    rating: "B",
    genre: "slice of life",
    user_id: 1,
  },
  {
    listItem: "Mirai Nikki",
    description:
      "When i frist watched it, it was my first experience with the genre and was quite enthralling",
    rating: "A",
    genre: "horror",
    user_id: 1,
  },
  {
    listItem: "Beelzebub",
    description:
      "Interesting premise with the demon baby and the progression was good",
    rating: "A",
    genre: "action",
    user_id: 1,
  },
  {
    listItem: "Danmachi",
    description: "Really fun cast and the city/ worldbuilding was interesting",
    rating: "B",
    genre: "adventure",
    user_id: 1,
  },
  {
    listItem: "Darling in the FranXX",
    description: "002 was funny as fuck",
    rating: "B",
    genre: "adventure",
    user_id: 1,
  },
  {
    listItem: "Toriko",
    description: "Foodwars is a better food anime",
    rating: "D",
    genre: "shounen",
    user_id: 1,
  },
  {
    listItem: "Golden Time",
    description: "Really fun romance",
    rating: "B",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "Yu Yu Hakusho",
    description: "really good cast ",
    rating: "A",
    genre: "shounen",
    user_id: 1,
  },
  {
    listItem: "Kill La Kill",
    description: "How are scissors sexual?",
    rating: "C",
    genre: "ecchi",
    user_id: 1,
  },
  {
    listItem: "Noragami",
    description: "Yato is the best delivery God",
    rating: "A",
    genre: "action",
    user_id: 1,
  },
  {
    listItem: "Akame ga Kill",
    description: "It is tragic how many deaths are in the show",
    rating: "B",
    genre: "action",
    user_id: 1,
  },
  {
    listItem: "High School Dxd",
    description: "Too many titty too little story",
    rating: "C",
    genre: "ecchi",
    user_id: 1,
  },
  {
    listItem: "Prince Of Tennis",
    description:
      "Ryoma is a cool character and I like the techniques in the first season",
    rating: "C",
    genre: "sports",
    user_id: 1,
  },
  {
    listItem: "Your Lie In April",
    description: "Really sad ending",
    rating: "S",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "Code Geass",
    description: "Lelouch is great. Nuff said",
    rating: "S",
    genre: "drama",
    user_id: 1,
  },
  {
    listItem: "Bakuman",
    description: "A show about romance and dreams. One of my favorites ever",
    rating: "",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "Soul Eater",
    description:
      "The anime ended poorly but the manga is the best i have ever read",
    rating: "A",
    genre: "action",
    user_id: 1,
  },
  {
    listItem: "Oregairu",
    description: "Really sad and funny slice of life / romance",
    rating: "A",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "Hataraku Maou",
    description: "the demon lord is a great mc donalds employee",
    rating: "B",
    genre: "action",
    user_id: 1,
  },
  {
    listItem: "Goblin Slayer",
    description: "Too much rape",
    rating: "F",
    genre: "ecchi",
    user_id: 1,
  },
  {
    listItem: "Masamune-kuns Revenge",
    description:
      "He felt he needed to get revenge but it was all a misunderstanding lmao",
    rating: "B",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "Owari no Seraph",
    description: "The story really pulled me in it was crazy good",
    rating: "A",
    genre: "drama",
    user_id: 1,
  },
  {
    listItem: "GATE",
    description: "I dropped it first season",
    rating: "D",
    genre: "magic",
    user_id: 1,
  },
  {
    listItem: "Kiss x Sis",
    description: "why do i do this to myself",
    rating: "D",
    genre: "ecchi",
    user_id: 1,
  },
  {
    listItem: "Kimi ni Todoke",
    description: "I droped the series",
    rating: "F",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "To Love-Ru",
    description: "A better DXD",
    rating: "C",
    genre: "ecchi",
    user_id: 1,
  },
  {
    listItem: "Charlotte",
    description: "I never could figure out the show it kept me on my toes",
    rating: "B",
    genre: "action",
    user_id: 1,
  },
  {
    listItem: "My little monster",
    description: "ANime about an asshole who fell in love with a normal girl.",
    rating: "C",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "Kobayashi=san Maid",
    description: "WTF dragon maid girls?",
    rating: "C",
    genre: "fantasy",
    user_id: 1,
  },
  {
    listItem: "A Certain Magical Index",
    description: "Pretty good verse",
    rating: "B",
    genre: "fantasy",
    user_id: 1,
  },
  {
    listItem: "Bunny Girl Senpai",
    description: "Really interesting characters",
    rating: "B",
    genre: "comedy",
    user_id: 1,
  },
  {
    listItem: "Musaigen no Phantom World",
    description:
      "You can't believe everything you see, or can't see, for that matter. In Musaigen no Phantom World, Phantoms, beings that blur the line between illusion and reality, wander around right under the noses of unsuspecting humans. Their origins are mysterious and few can see themーthat is, until a research facility bombing spreads a virus that grants the ability to. Humans with special powers are given the task of sealing the troublemaking Phantoms.",
    rating: "D",
    genre: "supernatural",
    user_id: 1,
  },
  {
    listItem: "Black Butler",
    description:
      "The relationship between sebastian and Ciel is super intriguing",
    rating: "A",
    genre: "action",
    user_id: 1,
  },
  {
    listItem: "Your name",
    description: "Wonderful animation, good story, minor plot holes",
    rating: "A",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "The Promised Neverland",
    description: "the dynamic between the siblings was pretty cool",
    rating: "A",
    genre: "horror",
    user_id: 1,
  },
  {
    listItem: "Relife",
    description:
      "Interesting show that made m think what i would do if i could redo life",
    rating: "B",
    genre: "school",
    user_id: 1,
  },
  {
    listItem: "Date A Live",
    description: "Crazy random plot",
    rating: "C",
    genre: "comedy",
    user_id: 1,
  },
  {
    listItem: "Shimoneta",
    description: "Dropped it was too wierd",
    rating: "F",
    genre: "ecchi",
    user_id: 1,
  },
  {
    listItem: "Sakamoto desu ga",
    description: "Fully Seinen Show",
    rating: "B",
    genre: "seinen",
    user_id: 1,
  },
  {
    listItem: "Kenichi",
    description: "I like the growth of the main character overall",
    rating: "A",
    genre: "action",
    user_id: 1,
  },
  {
    listItem: "Angel Beats",
    description: "Sad as fuck",
    rating: "C",
    genre: "drama",
    user_id: 1,
  },
  {
    listItem: "Yosuga no Sora",
    description: "Why is hentai on kissanime",
    rating: "D",
    genre: "ecchi",
    user_id: 1,
  },
  {
    listItem: "Boku wa Tomodachi ",
    description:
      "the main charcter is a lonely highschooler who makes friends with hot girl",
    rating: "C",
    genre: "ecchi",
    user_id: 1,
  },
  {
    listItem: "Shoujo Nozaki-kun",
    description: "I feel so bad for Chiyo Sakura",
    rating: "B",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "Saiki Kusuo",
    description: "Funny show good time",
    rating: "B",
    genre: "comedy",
    user_id: 1,
  },
  {
    listItem: "Clannad",
    description: "good romance my heart doki doki",
    rating: "B",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "Hajimete no Gal",
    description:
      "I thought it was just a series that had fanservice but it has some value ",
    rating: "C",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "Netoge no Yome",
    description: "Funny little romance about some gamers",
    rating: "B",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "AnoHana",
    description: "Sad shit",
    rating: "B",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "Chuunibyou demo Koi",
    description: "Delusional main character leads to some funny moments",
    rating: "C",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "Danganronpa",
    description: "Pretty good horror",
    rating: "B",
    genre: "horror",
    user_id: 1,
  },
  {
    listItem: "Absolute Duo",
    description:
      "The power system was pretty unique i liked the team battles a lot",
    rating: "B",
    genre: "action",
    user_id: 1,
  },
  {
    listItem: "So i can't play H",
    description: "meh",
    rating: "D",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "Free",
    description: "I love the character dynamics here",
    rating: "B",
    genre: "sports",
    user_id: 1,
  },
  {
    listItem: "Another",
    description: "Sad boi hours",
    rating: "C",
    genre: "horror",
    user_id: 1,
  },
  {
    listItem: "Yamada and the seven witches",
    description: "Interesting romance Ooo",
    rating: "B",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "Hunter X Hunter",
    description:
      "Really awesome fights, art, characters, power system, world building. its got it all",
    rating: "S",
    genre: "shounen",
    user_id: 1,
  },
  {
    listItem: "Fuuka",
    description: "its music",
    rating: "D",
    genre: "ecchi",
    user_id: 1,
  },
  {
    listItem: "Nagi no Asukara",
    description: "Underwater people see the upstairs",
    rating: "B",
    genre: "drama",
    user_id: 1,
  },
  {
    listItem: "Wotakoi",
    description: "Love be hard for gamers",
    rating: "B",
    genre: "drama",
    user_id: 1,
  },
  {
    listItem: "Tsurezure Children",
    description: "Funny Show good romanc",
    rating: "B",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "Domestic Girlfriend",
    description: "A dumpster fire i could not stop watching",
    rating: "B",
    genre: "romance",
    user_id: 1,
  },
  {
    listItem: "Durarara",
    description:
      "Interesting dynamic of characters and interesting city. The main character really suprised me",
    rating: "S",
    genre: "action",
    user_id: 1,
  },
  {
    listItem: "Steins Gate",
    description:
      "I love the psychological thoughts and perspective we got to see from okabe pushing through his limits of humanity and him finding his definiton of what it means to be human, and then him shattering it",
    rating: "S",
    genre: "psychological",
    user_id: 1,
  },
];
